In [1]:
import numpy as np 
a = np.zeros(shape = (3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
for i in range(3):
    for j in range(3):
        print("i:{}".format(i), "  j:", j)
        a[i][j] = i*j
print(a)

i:0   j: 0
i:0   j: 1
i:0   j: 2
i:1   j: 0
i:1   j: 1
i:1   j: 2
i:2   j: 0
i:2   j: 1
i:2   j: 2
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]


In [3]:
a = 5
if(a>2):
    print(a+8)
print("結束了")

13
結束了


In [4]:
# 好用套件
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

## 字典功能

In [5]:
mydict = { 'apple': '蘋果', 'banana': '香蕉' }

In [6]:
mydict['apple']

'蘋果'

In [7]:
mydict['orange'] = '橘子'

In [8]:
mydict

{'apple': '蘋果', 'banana': '香蕉', 'orange': '橘子'}

In [9]:
for i in mydict:
    print("{}：{}".format(i, mydict[i]))

banana：香蕉
apple：蘋果
orange：橘子


## 互動功能

In [10]:
from ipywidgets import interact

In [11]:
def f(x):
    print(x)

In [12]:
f(3)

3


In [13]:
f("hi")

hi


**interact(函數, 變數)**

In [14]:
interact(f, x=3)

interactive(children=(IntSlider(value=3, description='x', max=9, min=-3), Output()), _dom_classes=('widget-int…

<function __main__.f(x)>

In [15]:
interact(f, x=3.)

interactive(children=(FloatSlider(value=3.0, description='x', max=9.0, min=-3.0), Output()), _dom_classes=('wi…

<function __main__.f(x)>

In [16]:
interact(f, x=(1.,10.))

interactive(children=(FloatSlider(value=5.5, description='x', max=10.0, min=1.0), Output()), _dom_classes=('wi…

<function __main__.f(x)>

In [17]:
interact(f, x="我老了")

interactive(children=(Text(value='我老了', description='x'), Output()), _dom_classes=('widget-interact',))

<function __main__.f(x)>

In [18]:
interact(f, x=["台北", "台中", "台南", "高雄"])

interactive(children=(Dropdown(description='x', options=('台北', '台中', '台南', '高雄'), value='台北'), Output()), _dom…

<function __main__.f(x)>

In [19]:
interact(f, x={"台北":1, "台中":2, "台南":3, "高雄":4})

interactive(children=(Dropdown(description='x', options={'台北': 1, '高雄': 4, '台南': 3, '台中': 2}, value=1), Output…

<function __main__.f(x)>